log stderr all;

router id 192.168.55.5;

define MY_AS = 64500;
define MT_AS = 65455;
define MT_IP = 192.168.55.1;
define BIRD_IP = 192.168.55.5;

protocol device {
}

protocol static static_antifilter {
    ipv4;
    include "/etc/bird/generated/routes.conf";
}

filter export_to_mikrotik {
    bgp_community.add((65432,500));
    bgp_next_hop = BIRD_IP;
    accept;
}

protocol bgp mikrotik {
    local as MY_AS;
    neighbor MT_IP as MT_AS;
    source address BIRD_IP;
    multihop;

    ipv4 {
        import none;
        export filter export_to_mikrotik;
    };
}
